/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GuiActivation.java
 *
 * Created on 6/12/2011, 03:44:42 PM
 */
package org.Nicon.Personal.GuiUser.Nicon;

import javax.swing.JOptionPane;
import org.Nicon.Personal.LibCore.Obj.NiconAdministrator;
import org.Nicon.Personal.LibCore.Sbin.NiconSystemAdmin;

/**
 *
 * @author frederick
 */
public class GuiActivation extends javax.swing.JFrame {

    /** Creates new form GuiActivation */
    public GuiActivation() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JLnombres = new javax.swing.JLabel();
        JTnombres = new javax.swing.JTextField();
        JLapellidos = new javax.swing.JLabel();
        JTapellidos = new javax.swing.JTextField();
        JLdireccion = new javax.swing.JLabel();
        JTdireccion = new javax.swing.JTextField();
        JLcelular = new javax.swing.JLabel();
        JTcelular = new javax.swing.JTextField();
        JLemail = new javax.swing.JLabel();
        JTemail = new javax.swing.JTextField();
        JLloggin = new javax.swing.JLabel();
        JTloggin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JPassword = new javax.swing.JPasswordField();
        JBgrabar = new javax.swing.JButton();
        JBcancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JLciudad = new javax.swing.JLabel();
        JTciudad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nicon v 0.1 Activacion");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/Nicon/Personal/GuiUser/Images/Activation.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Activación del sistema");

        JLnombres.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        JLnombres.setText("- Nombres:");

        JTnombres.setFont(new java.awt.Font("Verdana", 0, 12));
        JTnombres.setToolTipText("Ingrese sus nombres");

        JLapellidos.setFont(new java.awt.Font("Verdana", 0, 12));
        JLapellidos.setText("- Apellidos:");

        JTapellidos.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        JTapellidos.setToolTipText("Ingrese sus apellidos");

        JLdireccion.setFont(new java.awt.Font("Verdana", 0, 12));
        JLdireccion.setText("- Dirección:");

        JTdireccion.setFont(new java.awt.Font("Verdana", 0, 12));
        JTdireccion.setToolTipText("Ingrese la direccion de su residencia");

        JLcelular.setFont(new java.awt.Font("Verdana", 0, 12));
        JLcelular.setText("- Número movil:");

        JTcelular.setFont(new java.awt.Font("Verdana", 0, 12));
        JTcelular.setToolTipText("Ingrese su número de telefono movil");

        JLemail.setFont(new java.awt.Font("Verdana", 0, 12));
        JLemail.setText("- Email:");

        JTemail.setFont(new java.awt.Font("Verdana", 0, 12));
        JTemail.setToolTipText("Ingrese su direccion de email");

        JLloggin.setFont(new java.awt.Font("Verdana", 0, 12));
        JLloggin.setText("- Loggin:");

        JTloggin.setFont(new java.awt.Font("Verdana", 0, 12));
        JTloggin.setToolTipText("Ingrese su loggin de registro");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12));
        jLabel3.setText("- Password: ");

        JPassword.setFont(new java.awt.Font("Verdana", 0, 12));
        JPassword.setToolTipText("Ingrese su password");

        JBgrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/Nicon/Personal/Images/ok.png"))); // NOI18N
        JBgrabar.setText("Activar");
        JBgrabar.setToolTipText("Activar el sistema con sus datos");
        JBgrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBgrabarActionPerformed(evt);
            }
        });

        JBcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/Nicon/Personal/Images/exit.png"))); // NOI18N
        JBcancelar.setText("Cancelar");
        JBcancelar.setToolTipText("salir del sistema");
        JBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBcancelarActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/Nicon/Personal/GuiUser/Images/Laptop.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setText("Nicon V 0.1");

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setText("Created in java");

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setText("Netbeans 7.0");

        JLciudad.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        JLciudad.setText("- Ciudad: ");

        JTciudad.setFont(new java.awt.Font("Verdana", 0, 12));
        JTciudad.setToolTipText("Ingrese su ciudad");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JLapellidos)
                                .addComponent(JLdireccion)
                                .addComponent(JLnombres))
                            .addGap(59, 59, 59)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JTnombres, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                .addComponent(JTdireccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                .addComponent(JTapellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLemail)
                            .addComponent(JLloggin)
                            .addComponent(jLabel3)
                            .addComponent(JLcelular)
                            .addComponent(JLciudad))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTciudad)
                            .addComponent(JPassword)
                            .addComponent(JTloggin)
                            .addComponent(JTcelular, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(JTemail, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(JBgrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JBcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155)))
                .addGap(114, 114, 114))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(159, 159, 159)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLnombres)
                            .addComponent(JTnombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLapellidos)
                            .addComponent(JTapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLdireccion)
                            .addComponent(JTdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLciudad)
                            .addComponent(JTciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel7)
                        .addGap(45, 45, 45))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLcelular)
                            .addComponent(JTcelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLemail)
                            .addComponent(JTemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLloggin)
                            .addComponent(JTloggin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(JPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBgrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBgrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBgrabarActionPerformed
        VerifyData();
    }//GEN-LAST:event_JBgrabarActionPerformed

    private void JBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBcancelarActionPerformed
        int response = JOptionPane.showConfirmDialog(rootPane, "¿ Esta seguro que desea cancelar la activación?", "Nicon Activación", JOptionPane.YES_NO_OPTION);
        if (response == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_JBcancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GuiActivation().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBcancelar;
    private javax.swing.JButton JBgrabar;
    private javax.swing.JLabel JLapellidos;
    private javax.swing.JLabel JLcelular;
    private javax.swing.JLabel JLciudad;
    private javax.swing.JLabel JLdireccion;
    private javax.swing.JLabel JLemail;
    private javax.swing.JLabel JLloggin;
    private javax.swing.JLabel JLnombres;
    private javax.swing.JPasswordField JPassword;
    private javax.swing.JTextField JTapellidos;
    private javax.swing.JTextField JTcelular;
    private javax.swing.JTextField JTciudad;
    private javax.swing.JTextField JTdireccion;
    private javax.swing.JTextField JTemail;
    private javax.swing.JTextField JTloggin;
    private javax.swing.JTextField JTnombres;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void VerifyData() {
        try {
            String nombres = this.JTnombres.getText();
            String apellidos = this.JTapellidos.getText();
            String direccion = this.JTdireccion.getText();
            String ciudad = this.JTciudad.getText();
            String celular = this.JTcelular.getText();
            String email = this.JTemail.getText();
            String loggin = this.JTloggin.getText();
            String pass = String.valueOf(this.JPassword.getPassword());

            if (nombres.equals("") || apellidos.equals("") || direccion.equals("") || ciudad.equals("") || celular.equals("") || email.equals("") || loggin.equals("") || pass.equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Hay campos sin Ingresar al registro por favor verifique e intente de nuevo", "Nicon Activación", JOptionPane.ERROR_MESSAGE);
            }else{
                NiconAdministrator administrator =new NiconAdministrator(nombres,apellidos,direccion,ciudad,celular,email,loggin,pass);
                NiconSystemAdmin.activeNiconPersonal(administrator);
                dispose();
            }
        } catch (Exception e) {
            System.err.println("Ocurrio un error en GuiActivation.VerifyData():\n");
            e.printStackTrace();
        }
    }
}
